import Verso
import VersoManual
import VersoBlueprint
import LeanMachineLearning.SequentialLearning.Deterministic
import LeanMachineLearning.SequentialLearning.FiniteActions
import LeanMachineLearning.SequentialLearning.IonescuTulceaSpace
import LeanMachineLearning.SequentialLearning.StationaryEnv
import LeanMachineLearning.Online.Bandit.ArrayProbSpace
import LeanMachineLearning.Online.Bandit.Regret
import LeanMachineLearning.Online.Bandit.RewardByCountMeasure
import LMLBlueprint.References
import LMLBlueprint.TeXPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Stochastic multi-armed bandits" =>

A bandit algorithm is an algorithm in the sense of Definition TODO FIND OUT HOW TO REFERENCE OUTSIDE OF ENVIRONMENTS.
We call the actions _arms_ and the observations _rewards_.

The first arm pulled by the algorithm is sampled from $`P_0`, the arm pulled at time $`1` is sampled from $`\pi_0(H_0)`, in which $`H_0 \in \mathcal{A} \times \mathcal{R}` is the data of the first arm pulled and the first observation received, and so on.

A stochastic bandit is simply a reward distribution for each arm: a Markov kernel $`\nu : \mathcal{A} \rightsquigarrow \mathbb{R}`, conditional distribution of the rewards given the arm pulled.
It is a stationary environment in which the observation space is $`\mathcal{R} = \mathbb{R}`.

An algorithm can interact with a bandit to produce a sequence of arms and rewards: after a time $`t`, the history $`H_t \in (\mathcal{A} \times \mathcal{R})^{t+1}` contains the arms pulled and rewards received up to that time,
- the algorithm chooses an arm $`A_{t+1}` sampled according to its policy $`\pi_t(H_t)`,
- the bandit generates a reward $`R_{t+1}` according to the distribution $`\nu(A_{t+1})`,
- the history is updated to $`H_{t+1} = ((A_0, R_0), \ldots, (A_{t+1}, R_{t+1}))`.



# The array model of rewards

:::group "bandit_space"
Probability space for stochastic multi-armed bandits
:::

We previously built a probability space on which we can define the sequence of arms and rewards generated by the interaction between the algorithm and the bandit, using the Ionescu-Tulcea theorem.
From Theorem isAlgEnvSeq\_unique (TODO REF), we know that the law of the sequence of arms and rewards is independent of the probability space used to define them.
Nonetheless, we now build an alternative model of the rewards, on which it will be easier to prove concentration inequalities.
By the uniqueness of the law, these statements will then transfer to any algorithm-environment interaction.

In the _array model_, we consider a probability space on which we have an infinite array of rewards from each arm, independent from each other.
When pulling an arm, the algorithm sees the next previously unseen reward from that arm in the array.

:::definition "arrayMeasure" (parent := "bandit_space") (lean := "Bandits.ArrayModel.arrayMeasure, Bandits.ArrayModel.probSpace")
Let $`I = [0,1]` and let $`P_U` be the uniform distribution on $`I`. We define the probability space $`(\Omega_{\mathcal{A}}, P_{\mathcal{A}})`, where
- $` \Omega_{\mathcal{A}} := I^{\mathbb{N}} \times \mathcal{R}^{\mathbb{N} \times \mathcal{A}}` ,
- $`P_{\mathcal{A}} := \left( \bigotimes_{n \in \mathbb{N}} P_U \right) \otimes \left( \bigotimes_{n \in \mathbb{N}, a \in \mathcal{A}} \nu(a) \right)` .

Uses: {uses "ionescu-tulcea"}[].
:::


:::definition "algFunction" (parent := "bandit_space") (lean := "Bandits.ArrayModel.algFunction, Bandits.ArrayModel.initAlgFunction")
Let $`\mathfrak{A}` be an {uses "algorithm"}[algorithm] with action space $`\mathcal{A}` and reward space $`\mathcal{R}`, policy $`\pi` and initial distribution $`P_0`.
For $`\mathcal{A}` and $`\mathcal{R}` standard Borel spaces, there exists jointly measurable functions $`f'_0 : I \to \mathcal{A}` and $`f_t : (\mathcal{A} \times \mathcal{R})^{t+1} \times I \to \mathcal{A}` such that
- the law of $`f'_0` is $`P_0`,
- for all history $`h_t \in (\mathcal{A} \times \mathcal{R})^{t+1}`, the law of $`f_t(h_t, \cdot)` is $`\pi_t(h_t)`.
:::


:::definition "AM.history" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hist, Bandits.ArrayModel.action, Bandits.ArrayModel.reward")
The history, actions and rewards on the {uses "arrayMeasure"}[array model probability space] $`(\Omega_{\mathcal{A}}, P_{\mathcal{A}})` are defined as follows:
- the action at time $`0` is $`A_0(\omega) = f'_0(\omega_{1,0})`, the reward at time $`0` is $`R_0(\omega) = \omega_{2,0,A_0(\omega)}`, and the history at time $`0` is $`H_0(\omega) = (A_0(\omega), R_0(\omega))`,
- for $`t \ge 0`, the action at time $`t+1` is $`A_{t+1}(\omega) = f_t(H_t(\omega), \omega_{1,t+1})`, the reward at time $`t+1` is $`R_{t+1}(\omega) = \omega_{2,N_{t+1,A_{t+1}(\omega)},A_{t+1}(\omega)}`, and the history at time $`t+1` is $`H_{t+1}(\omega) = (H_t(\omega), (A_{t+1}(\omega), R_{t+1}(\omega)))`.

Uses: {uses "algFunction"}[], {uses "pullCount"}[].
:::


The goal of this section is to show that $`(\Omega_{\mathcal{A}}, P_{\mathcal{A}})` with the actions and rewards defined above is an algorithm-environment sequence.



## Measurability

TODO: some of those results are proved for $`\mathcal{A}` countable. Add that assumption where needed.

*Remark: Proving measurability with respect to a sub-sigma-algebra*

In this section, we often need to prove that a random variable $`X` is measurable with respect to the sigma-algebra generated by a subset of the independent random variables defining the probability space $`\Omega_{\mathcal{A}}`.
We want to prove that $`X : \Omega_{\mathcal{A}} \to \mathcal{X}` is measurable with respect to the sigma-algebra $`\sigma((\omega_p)_{p \in S})`, where $`S` is a subset of the indices of the independent random variables defining $`\Omega_{\mathcal{A}}`.
In most cases, this is due to $`X` being defined (possibly recursively in a complicated way) only using those random variables.
However, it might be difficult to exhibit an explicit function $`f` such that $`X = f((\omega_p)_{p \in S})`.

Here is a general strategy to prove such measurability results in Lean:
1. Prove that $`X` is measurable with respect to the full sigma-algebra on $`\Omega_{\mathcal{A}}`.
2. Prove a congruence lemma: for any $`\omega, \omega' \in \Omega_{\mathcal{A}}`, if $`\omega_p = \omega'_p` for all $`p \in S`, then $`X(\omega) = X(\omega')`.
3. Define $`g : (\prod_{p \in S} \Omega_p) \to \Omega` by $`g((\omega_p)_{p \in S}) = \omega'`, where $`\omega'_p = \omega_p` for $`p \in S` and $`\omega'_p` is some fixed value for $`p \notin S`.
4. Write $`X = X \circ g \circ \mathrm{proj}_S`, where $`\mathrm{proj}_S : \Omega_{\mathcal{A}} \to \prod_{p \in S} \Omega_p` is the projection on the coordinates in $`S`.
5. Conclude that $`X` is the composition of a measurable function $`(X \circ g)` and the random variable generating the sub-sigma-algebra, and thus is measurable with respect to that sub-sigma-algebra.


:::lemma_ "AM.measurable_hist" (parent := "bandit_space") (lean := "Bandits.ArrayModel.measurable_hist, Bandits.ArrayModel.measurable_action, Bandits.ArrayModel.measurable_reward")
$`H_t`, $`N_{t,A_t}`, $`A_t` and $`R_t` are measurable for all $`t \in \mathbb{N}`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[].
:::

:::proof "AM.measurable_hist"
Uses: {uses "AM.history"}[].
:::


:::lemma_ "AM.hist_congr" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hist_congr")
Let $`\omega, \omega' \in \Omega_{\mathcal{A}}` and $`t \in \mathbb{N}`.
Suppose that
- $`\forall s \le t, \ \omega_{1,s} = \omega'_{1,s}` ,
- $`\forall a \in \mathcal{A}, \forall s < N_{t+1,a}, \ \omega_{2,s,a} = \omega'_{2,s,a}` .

Then $`H_t(\omega) = H_t(\omega')`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::

:::proof "AM.hist_congr"
Uses: {uses "AM.history"}[], {uses "pullCount_basic"}[].
:::


:::lemma_ "AM.stepsUntil_congr" (parent := "bandit_space") (lean := "Bandits.ArrayModel.stepsUntil_congr")
Let $`\omega, \omega' \in \Omega_{\mathcal{A}}`, $`t, m \in \mathbb{N}` and $`a \in \mathcal{A}`.
Suppose that
- $` \omega_{1} = \omega'_{1}` ,
- $`\forall s < m, \ \omega_{2,s,a} = \omega'_{2,s,a}` ,
- $`\forall b \ne a, \forall s \in \mathbb{N}, \ \omega_{2,s,b} = \omega'_{2,s,b}` .

Then $`(N_{t+1, a}(\omega) = m \wedge A_{t+1}(\omega) = a) \iff (N_{t+1, a}(\omega') = m \wedge A_{t+1}(\omega') = a)`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::

:::proof "AM.stepsUntil_congr"
Uses: {uses "AM.history"}[], {uses "AM.hist_congr"}[].
:::


:::definition "AM.probSpaceSubsets" (parent := "bandit_space") (lean := "Bandits.ArrayModel.truePast")
We define the following functions on $`\Omega_{\mathcal{A}}`:
- $`F_{1, t}(\omega) = ((\omega_{1,s})_{s \le t}, (\omega_{2,s})_{s \in \mathbb{N}})` ,
- $`F_{2, a, t}(\omega) = ((\omega_{1,s})_{s \in \mathbb{N}}, (\omega_{2, \min\{s,N_{t+1,a}(\omega)-1\}, a})_{s \in \mathbb{N}}, (\omega_{2, s, b})_{s \in \mathbb{N}, b \ne a})` ,
- $`F_{2, a}^m(\omega) = ((\omega_{1,s})_{s \in \mathbb{N}}, (\omega_{2, \min\{s,m-1\}, a})_{s \in \mathbb{N}}, (\omega_{2, s, b})_{s \in \mathbb{N}, b \ne a})` .

In the definition of $`F_{2, a, t}` and $`F_{2, a}^m`, if $`N_{t+1,a}(\omega) = 0` (resp. $`m = 0`), then the second component is a constant sequence equal to an arbitrary value.

$`F_{1, t}(\omega)` contains all the information in $`\omega` except for the action selection randomness after time $`t`.

$`F_{2, a, t}(\omega)` contains all the information in $`\omega` except the rewards for arm $`a` indexed by $`N_{t+1,a}(\omega)` or more.
$`F_{2, a}^m(\omega)` is similar, but removes the rewards for arm $`a` indexed by $`m` or more.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::


:::lemma_ "AM.measurable_hist_todo" (parent := "bandit_space") (lean := "Bandits.ArrayModel.measurable_hist_todo, Bandits.ArrayModel.measurable_hist_truePast")
For all $`t \in \mathbb{N}`, $`H_t` is measurable with respect to the sigma-algebra generated by $`F_{1, t}`, and with respect to the sigma-algebra generated by $`F_{2, a, t}` for any arm $`a \in \mathcal{A}`.

Uses : {uses "algorithm"}[], {uses "AM.probSpaceSubsets"}[].
:::

:::proof "AM.measurable_hist_todo"
Uses: {uses "AM.measurable_hist"}[], {uses "pullCount"}[], {uses "AM.hist_congr"}[].
:::


:::lemma_ "AM.measurable_action_add_one_truePast" (parent := "bandit_space") (lean := "Bandits.ArrayModel.measurable_action_add_one_truePast")
$`A_{t+1}` is measurable with respect to the sigma-algebra generated by $`F_{2, a, t}` for any arm $`a \in \mathcal{A}`.

Uses : {uses "algorithm"}[], {uses "AM.probSpaceSubsets"}[].
:::

:::proof "AM.measurable_action_add_one_truePast"
  Uses: {uses "AM.measurable_hist_todo"}[], .
:::


:::lemma_ "AM.measurable_pullCount_add_one_truePast" (parent := "bandit_space") (lean := "Bandits.ArrayModel.measurable_pullCount_add_one_truePast")
$`N_{t+1,a}` is measurable with respect to the sigma-algebra generated by $`F_{2, a, t}`.

Uses: {uses "AM.history"}[], {uses "arrayMeasure"}[], {uses "algorithm"}[], {uses "AM.probSpaceSubsets"}[], {uses "pullCount"}[].
:::

:::proof "AM.measurable_pullCount_add_one_truePast"
  Uses: {uses "AM.measurable_hist_todo"}[].
:::


:::lemma_ "AM.measurable_stepsUntil" (parent := "bandit_space") (lean := "Bandits.ArrayModel.measurable_stepsUntil")
For $`t, m \in \mathbb{N}` and $`a \in \mathcal{A}`, the indicator function $`\mathbb{I}\{N_{t+1,a} = m \wedge A_{t+1} = a\} : \Omega_{\mathcal{A}} \to \{0, 1\}` is measurable with respect to the sigma-algebra generated by $`F_{2, a}^m`.

Uses: {uses "AM.history"}[], {uses "arrayMeasure"}[], {uses "algorithm"}[], {uses "pullCount"}[], {uses "AM.probSpaceSubsets"}[].
:::

:::proof "AM.measurable_stepsUntil"
  Uses: {uses "AM.measurable_hist"}[], {uses "AM.stepsUntil_congr"}[].
:::


:::lemma_ "AM.measurable_pullCount_action_add_one_hist" (parent := "bandit_space") (lean := "Bandits.ArrayModel.measurable_pullCount_action_add_one_hist")
For $`t \in \mathbb{N}`, the function $`N_{t+1, A_{t+1}}` is measurable with respect to the sigma-algebra generated by $`H_t` and $`A_{t+1}`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::

:::proof "AM.measurable_pullCount_action_add_one_hist"
:::



## Independence


:::lemma_ "AM.indepFun_fst_add_one_aux" (parent := "bandit_space") (lean := "Bandits.ArrayModel.indepFun_fst_add_one_aux")
$`\omega \mapsto \omega_{1, t+1}` is independent of $`F_{1, t}`.

Uses: {uses "AM.probSpaceSubsets"}[].
:::


:::lemma_ "AM.indepFun_fst_add_one_hist" (parent := "bandit_space") (lean := "Bandits.ArrayModel.indepFun_fst_add_one_hist")
$`\omega \mapsto \omega_{1, t+1}` is independent of $`H_t`.

Uses: {uses "algorithm"}[], {uses "AM.probSpaceSubsets"}[].
:::

:::proof "AM.indepFun_fst_add_one_hist"
  Uses: {uses "AM.measurable_hist_todo"}[], {uses "AM.indepFun_fst_add_one_aux"}[]
:::


:::lemma_ "AM.indepFun_snd_apply_aux" (parent := "bandit_space") (lean := "Bandits.ArrayModel.indepFun_snd_apply_aux")
For $`a \in \mathcal{A}` and $`m \in \mathbb{N}`, $`\omega \mapsto \omega_{2, m, a}` is independent of $`F_{2, a}^m`.

Uses: {uses "AM.probSpaceSubsets"}[].
:::



:::lemma_ "AM.indepFun_snd_apply_pullCount_action" (parent := "bandit_space") (lean := "Bandits.ArrayModel.indepFun_snd_apply_pullCount_action")
For $`a \in \mathcal{A}` and $`m \in \mathbb{N}`, $`\omega \mapsto \omega_{2, m, a}` is independent of the indicator function $`\mathbb{I}\{N_{t+1,a} = m \wedge A_{t+1} = a\}`.

Uses: {uses "algorithm"}[], {uses "pullCount"}[], {uses "AM.probSpaceSubsets"}[].
:::

:::proof "AM.indepFun_snd_apply_pullCount_action"
  Uses: {uses "AM.indepFun_snd_apply_aux"}[], {uses "AM.measurable_stepsUntil"}[]
:::


:::lemma_ "AM.indepFun_snd_hist_cond" (parent := "bandit_space") (lean := "Bandits.ArrayModel.indepFun_snd_hist_cond")
For $`a \in \mathcal{A}` and $`t, m \in \mathbb{N}`, $`\omega \mapsto \omega_{2, m, a}` is independent of $`H_t` given that $`N_{t+1,a} = m` and $`A_{t+1} = a`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::

:::proof "AM.indepFun_snd_hist_cond"
  Uses: {uses "AM.measurable_hist_todo"}[], {uses "AM.measurable_hist"}[], {uses "AM.indepFun_snd_apply_aux"}[], {uses "AM.measurable_stepsUntil"}[], {uses "AM.probSpaceSubsets"}[].
:::




## Laws


:::lemma_ "AM.hasLaw_action_zero" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hasLaw_action_zero")
The law of $`A_0` in the array model is $`P_0`.

Uses : {uses "AM.history"}[], {uses "algorithm"}[].
:::

:::proof "AM.hasLaw_action_zero"
  Uses: {uses "AM.measurable_hist"}[]
:::


:::lemma_ "AM.hasCondDistrib_reward_zero" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hasCondDistrib_reward_zero")
In the array model, $`P_{\mathcal{A}}(R_0 \mid A_0) = \nu`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[].
:::

:::proof "AM.hasCondDistrib_reward_zero"
  Uses: {uses "AM.measurable_hist"}[], {uses "condDistrib_ae_eq_cond"}[]
:::


:::lemma_ "AM.hasCondDistrib_action" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hasCondDistrib_action")
In the array model, $`P_{\mathcal{A}}(A_{t+1} \mid H_t) = \pi_t`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[].
:::

:::proof "AM.hasCondDistrib_action"
  Uses: {uses "AM.measurable_hist"}[], {uses "AM.indepFun_fst_add_one_hist"}[]
:::


:::lemma_ "AM.hasCondDistrib_reward_pullCount_action" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hasCondDistrib_reward_pullCount_action")
In the array model, $`P_{\mathcal{A}}(R_{t+1} \mid N_{t+1,A_{t+1}}, A_{t+1}) = \nu`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::

:::proof "AM.hasCondDistrib_reward_pullCount_action"
  Uses: {uses "AM.indepFun_snd_apply_pullCount_action"}[], {uses "AM.measurable_hist"}[], {uses "pullCount_basic"}[], {uses "condDistrib_ae_eq_cond"}[]
:::


:::lemma_ "AM.hasCondDistrib_reward_hist_action_pullCount" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hasCondDistrib_reward_hist_action_pullCount")
In the array model, $`P_{\mathcal{A}}(R_{t+1} \mid H_t, A_{t+1}, N_{t+1,A_{t+1}}) = \nu`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[].
:::

:::proof "AM.hasCondDistrib_reward_hist_action_pullCount"
  Uses: {uses "AM.indepFun_snd_apply_pullCount_action"}[], {uses "AM.indepFun_snd_hist_cond"}[], {uses "AM.measurable_hist"}[], {uses "pullCount_basic"}[]
:::


:::lemma_ "AM.condIndepFun_reward_hist" (parent := "bandit_space") (lean := "Bandits.ArrayModel.condIndepFun_reward_hist")
For $`t \ge 0`, $`R_{t+1} \ind H_t \mid A_{t+1}, N_{t+1, A_{t+1}}`.

Uses: {uses "AM.history"}[], {uses "algorithm"}[], {uses "pullCount"}[], {uses "AM.measurable_hist"}[].
:::

:::proof "AM.condIndepFun_reward_hist"
  Uses: {uses "AM.measurable_hist"}[], {uses "AM.hasCondDistrib_reward_hist_action_pullCount"}[]
:::


:::lemma_ "AM.hasCondDistrib_reward" (parent := "bandit_space") (lean := "Bandits.ArrayModel.hasCondDistrib_reward")
In the array model, $`P_{\mathcal{A}}(R_{t+1} \mid H_t, A_{t+1}) = \nu`.

Uses: {uses "AM.history"}[], {uses "stationaryEnv"}[], {uses "environment"}[], {uses "algorithm"}[].
:::

:::proof "AM.hasCondDistrib_reward"
  Uses: {uses "AM.measurable_pullCount_action_add_one_hist"}[], {uses "AM.hasCondDistrib_reward_pullCount_action"}[], {uses "AM.measurable_hist"}[], {uses "AM.condIndepFun_reward_hist"}[], {uses "pullCount"}[]
:::


:::theorem "isAlgEnvSeq_arrayMeasure" (parent := "bandit_space") (lean := "Bandits.ArrayModel.isAlgEnvSeq_arrayMeasure")
The actions and rewards defined on the array model probability space $`(\Omega_{\mathcal{A}}, P_{\mathcal{A}})` form an algorithm-environment sequence for the algorithm $`\mathfrak{A}` and bandit $`\nu`.

Uses: {uses "AM.history"}[], {uses "stationaryEnv"}[], {uses "IsAlgEnvSeq"}[].
:::

:::proof "isAlgEnvSeq_arrayMeasure"
The four conditions of {uses "IsAlgEnvSeq"}[] are satisfied by {uses "AM.hasLaw_action_zero"}[], {uses "AM.hasCondDistrib_reward_zero"}[], {uses "AM.hasCondDistrib_action"}[] and {uses "AM.hasCondDistrib_reward"}[].
:::



# Law of the n-th pull

:::group "rewardByCount_law"
Law of the n-th pull
:::

This section describes the law of $`Y_{n, a}` the $`n^{th}` reward obtained from an arm $`a \in \mathcal{A}`.

We augment the probability space $`\Omega` on which we have an algorithm-environment sequence with $`\Omega' = \mathbb{R}^{\mathbb{N} \times \mathcal{A}}`, on which we put the product measure $`\bigotimes_{n \in \mathbb{N}, a \in \mathcal{A}} \nu(a)`.
With that measure, the law of $`Z_{n,a}` is $`\nu(a)`.


:::lemma_ "measurable_comap_indicator_stepsUntil_eq" (parent := "rewardByCount_law") (lean := "Learning.measurable_comap_indicator_stepsUntil_eq")
The function $`\mathbb{I}\{T_{n,a} = t\} : \Omega \to \{0, 1\}` is measurable with respect to the sigma-algebra generated by $`(H_{t-1}, A_t)`.

Uses: {uses "history"}[], {uses "stepsUntil"}[].
:::

:::proof "measurable_comap_indicator_stepsUntil_eq"
  Uses: {uses "stepsUntil_basic"}[], {uses "pullCount_basic"}[], {uses "pullCount"}[], {uses "IsAlgEnvSeq.filtration"}[].
:::


:::lemma_ "CondIndepFun.prod_right" (lean := "ProbabilityTheory.CondIndepFun.prod_right")
If $`X \ind Y \mid Z`, then $`X \ind (Y, Z) \mid Z`.
:::


:::lemma_ "condIndepFun_reward_stepsUntil_arm" (parent := "rewardByCount_law") (lean := "Bandits.condIndepFun_reward_stepsUntil_action")
For $`t > 0`, $`R_t \ind \mathbb{I}\{T_{n, a} = t\} \mid A_t`.

Uses: {uses "stationaryEnv"}[], {uses "IsAlgEnvSeq"}[], {uses "ionescu-tulcea"}[], {uses "stepsUntil"}[].
:::

:::proof "condIndepFun_reward_stepsUntil_arm"
$`\mathbb{I}\{T_{n, a} = t\}` is measurable with respect to the sigma-algebra generated by $`(H_{t-1}, A_t)` by {uses "measurable_comap_indicator_stepsUntil_eq"}[].

It thus suffices to show that $`R_t \ind (H_{t-1}, A_t) \mid A_t`, which is implied by $`R_t \ind H_{t-1} \mid A_t` ({uses "CondIndepFun.prod_right"}[]), which is {uses "condIndepFun_reward_hist_action"}[].

Uses: {uses "condIndepFun_reward_hist_action"}[], {uses "CondIndepFun.prod_right"}[], {uses "stepsUntil_basic"}[], {uses "measurable_comap_indicator_stepsUntil_eq"}[], {uses "history"}[], {uses "pullCount"}[].
:::


:::lemma_ "reward_cond_stepsUntil" (parent := "rewardByCount_law") (lean := "Bandits.reward_cond_stepsUntil")
Let $`n > 0`, $`t \in \mathbb{N}` and suppose that $`P(T_{n, a} = t) > 0`.
Then $`P(R_t \mid T_{n, a} = t) = \nu(a)`.

Uses: {uses "stationaryEnv"}[], {uses "IsAlgEnvSeq"}[], {uses "ionescu-tulcea"}[], {uses "stepsUntil"}[].
:::

:::proof "reward_cond_stepsUntil"
First, if $`T_{n, a} = t`, then $`A_t = a` ({uses "stepsUntil_basic"}[]), such that $`P(R_t \mid T_{n, a} = t) = P(R_t \mid T_{n, a} = t, A_t = a)`.

Then, using first the independence from {uses "condIndepFun_reward_stepsUntil_arm"}[] and then the conditional distribution from {uses "condDistrib_reward_stationaryEnv"}[], we have
$$`
  P(R_t \mid T_{n, a} = t, A_t = a)
  = P(R_t \mid A_t = a)
  = \nu(a)
  \: .
`

Uses: {uses "environment"}[], {uses "stepsUntil_basic"}[], {uses "condIndepFun_reward_stepsUntil_arm"}[], {uses "pullCount"}[], {uses "condDistrib_ae_eq_cond"}[], {uses "condDistrib_reward_stationaryEnv"}[]
:::


:::lemma_ "condDistrib_ae_eq_cond" (lean := "ProbabilityTheory.condDistrib_ae_eq_cond")
For a random variable $`X` on a countable space with the discrete sigma algebra, $`P(Y \mid X) = (x \mapsto P(Y \mid X = x))`, $`(X_*P)`-almost surely.
Furthermore, that almost sure equality means that for all $`x` such that $`P(X = x) > 0`, we have $`P(Y \mid X = x) = P(Y \mid X)(x)`.
:::


:::lemma_ "condDistrib_rewardByCount_stepsUntil" (parent := "rewardByCount_law") (lean := "Bandits.condDistrib_rewardByCount_stepsUntil")
For $`n > 0` and $`t \in \mathbb{N}`, $`P(Y_{n,a} \mid T_{n,a}) = \nu(a)` (in which the measure on the r.h.s. is seen as a constant kernel).

Uses: {uses "stationaryEnv"}[], {uses "IsAlgEnvSeq"}[], {uses "ionescu-tulcea"}[], {uses "rewardByCount"}[], {uses "stepsUntil"}[].
:::

:::proof "condDistrib_rewardByCount_stepsUntil"
It suffices to show that for all $`t \in \mathbb{N} \cup \{\infty\}` such that $`P(T_{n, a} = t) > 0`, the law of $`Y_{n,a}` conditioned on $`T_{n,a} = t` is $`\nu(a)`.

If $`t < \infty`, then $`P(Y_{n, a} \mid T_{n, a = t}) = P(R_t \mid T_{n, a} = t) = \nu(a)` by {uses "reward_cond_stepsUntil"}[].

If $`t = \infty`, then $`P(Y_{n, a} \mid T_{n, a} = \infty) = P(Z_{n, a} \mid T_{n, a} = \infty)`. By independence of $`Z_{n,a}` and $`T_{n, a}`, this is just $`\nu(a)`, the law of $`Z_{n,a}`.

Uses: {uses "environment"}[], {uses "reward_cond_stepsUntil"}[], {uses "pullCount"}[], {uses "condDistrib_ae_eq_cond"}[]
:::


:::lemma_ "hasLaw_rewardByCount" (parent := "rewardByCount_law") (lean := "Bandits.hasLaw_rewardByCount")
For $`n > 0` and $`a \in \mathcal{A}`, $`(Y_{n,a})_*P = \nu(a)`.

Uses: {uses "stationaryEnv"}[], {uses "IsAlgEnvSeq"}[], {uses "ionescu-tulcea"}[], {uses "rewardByCount"}[]
:::

:::proof "hasLaw_rewardByCount"
The law of $`Y_{n,a}` is given by $`(Y_{n, a})_*P = P(Y_{n, a} \mid T_{n, a}) \circ (T_{n, a})_*P`.
By {uses "condDistrib_rewardByCount_stepsUntil"}[], $`P(Y_{n, a} \mid T_{n, a}) = \nu(a)`, a constant kernel.
Thus the composition is just $`\nu(a)`.

Uses: {uses "environment"}[], {uses "condDistrib_rewardByCount_stepsUntil"}[], {uses "stepsUntil"}[], {uses "pullCount"}[].
:::



# Regret and other bandit quantities

:::group "regret"
Regret and other bandit quantities
:::

For an arm $`a \in \mathcal{A}`, we denote by $`\mu_a` the mean of the rewards for that arm, that is $`\mu_a = \nu(a)[\mathrm{id}]`.
We denote by $`\mu^*` the mean of the best arm, that is $`\mu^* = \max_{a \in \mathcal{A}} \mu_a`.


:::definition "regret" (parent := "regret") (lean := "Bandits.regret")
The regret $`R_T` of a sequence of arms $`A_0, \ldots, A_{T-1}` after $`T` pulls is the difference between the cumulative reward of always playing the best arm and the cumulative reward of the sequence:
$$`
  R_T = T \mu^* - \sum_{t=0}^{T-1} \mu_{A_t} \: .
`
:::

TODO: the $`R_T` notation clashes with the random variable $`R_t`.

:::definition "gap" (parent := "regret") (lean := "Bandits.gap")
For an arm $`a \in \mathcal{A}`, its gap is defined as the difference between the mean of the best arm and the mean of that arm: $`\Delta_a = \mu^* - \mu_a`.
:::


:::lemma_ "sum_pullCount_mul" (parent := "regret") (lean := "Learning.sum_pullCount_mul")
Let $`f : \mathcal{A} \to \mathbb{R}` be a function on the arms. For all $`t \in \mathbb{N}`,
$$`
  \sum_{a \in \mathcal{A}} N_{t,a} f(a) = \sum_{s=0}^{t-1} f(A_s) \: .
`

Uses: {uses "pullCount"}[].
:::

:::proof "sum_pullCount_mul"
$$`
  \sum_{a \in \mathcal{A}} N_{t,a} f(a)
  &= \sum_{a \in \mathcal{A}} \sum_{s=0}^{t-1} \mathbb{I}\{A_s = a\} f(a)
  \\
  &= \sum_{s=0}^{t-1} \sum_{a \in \mathcal{A}} \mathbb{I}\{A_s = a\} f(a)
  \\
  &= \sum_{s=0}^{t-1} f(A_s)
  \: .
`
:::


:::lemma_ "regret_eq_sum_pullCount_mul_gap" (parent := "regret") (lean := "Bandits.regret_eq_sum_pullCount_mul_gap")
For $`\mathcal{A}` finite, the {uses "regret"}[regret] $`R_T` can be expressed as a sum over the arms and their {uses "gap"}[gaps]:
$$`
  R_T = \sum_{a \in \mathcal{A}} N_{T,a} \Delta_a \: .
`

Uses: {uses "pullCount"}[].
:::

:::proof "regret_eq_sum_pullCount_mul_gap"
Apply {uses "sum_pullCount_mul"}[] with $`f(a) = \Delta_a` to obtain:
$$`
  \sum_{a \in \mathcal{A}} N_{T,a} \Delta_a
  &= \sum_{s=0}^{T-1} \Delta_{A_s}
  \\
  &= \sum_{s=0}^{T-1} \mu^* - \sum_{s=0}^{T-1} \mu_{A_s}
  \\
  &= R_T
  \: .
`
:::


:::lemma_ "integral_regret_eq_sum_mul" (parent := "regret") (lean := "Bandits.integral_regret_eq_sum_gap_mul_integral_pullCount")
For $`\mathcal{A}` finite, the expected {uses "regret"}[regret] can be expressed as a sum over the arms and their {uses "gap"}[gaps]:
$$`
  P[R_T] = \sum_{a \in \mathcal{A}}P[N_{T,a}] \Delta_a \: .
`

Uses: {uses "pullCount"}[].
:::

:::proof "integral_regret_eq_sum_mul"
Uses: {uses "regret_eq_sum_pullCount_mul_gap"}[].
:::
